version: '2'
services:
  eveserver:
    image: ondebleue/eve-server
    env_file:
      - ${PWD}/config/env
    volumes:
      - ${PWD}/log:/var/log/supervisor
    restart: always

  nginx:
    image: nginx:1.9
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/config/nginx:/etc/nginx/conf.d
      - ${PWD}/letsencrypt/etc:/etc/letsencrypt
      - ${PWD}/log:/var/log/nginx
    links:
      - eveserver:eveserver
    restart: always
